-- 0022: PHASE 3 — core backend + projects + conversations + workspace persistence.
-- Extends the frozen schema; existing tables/columns are never dropped or renamed.

-- ---------------------------------------------------------------------------
-- Projects
-- ---------------------------------------------------------------------------

-- Full status set: ACTIVE / ARCHIVED / COMPLETED / ON_HOLD
ALTER TABLE projects DROP CONSTRAINT projects_status_check;
ALTER TABLE projects ADD CONSTRAINT projects_status_check
  CHECK (status IN ('ACTIVE','ARCHIVED','COMPLETED','ON_HOLD'));

ALTER TABLE projects ADD COLUMN deadline      timestamptz;
ALTER TABLE projects ADD COLUMN is_favorite   boolean NOT NULL DEFAULT false;
ALTER TABLE projects ADD COLUMN tags          text[] NOT NULL DEFAULT '{}';

CREATE INDEX idx_projects_owner_status ON projects (owner_id, status);
CREATE INDEX idx_projects_owner_favorite ON projects (owner_id, is_favorite) WHERE is_favorite;

-- Project membership roles: owner / admin / editor / member / viewer
ALTER TABLE project_members DROP CONSTRAINT project_members_role_check;
ALTER TABLE project_members ADD CONSTRAINT project_members_role_check
  CHECK (role IN ('owner','admin','editor','member','viewer'));

-- ---------------------------------------------------------------------------
-- Conversations
-- ---------------------------------------------------------------------------

ALTER TABLE conversations ADD COLUMN archived         boolean NOT NULL DEFAULT false;
ALTER TABLE conversations ADD COLUMN is_favorite      boolean NOT NULL DEFAULT false;
ALTER TABLE conversations ADD COLUMN tags             text[] NOT NULL DEFAULT '{}';
ALTER TABLE conversations ADD COLUMN sharing          jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE conversations ADD COLUMN search_metadata  jsonb NOT NULL DEFAULT '{}'::jsonb;

CREATE INDEX idx_conversations_owner_favorite ON conversations (owner_id, is_favorite) WHERE is_favorite;
CREATE INDEX idx_conversations_owner_archived ON conversations (owner_id, archived) WHERE archived;

-- ---------------------------------------------------------------------------
-- Messages: deterministic ordering, edit-history metadata, thread links
-- ---------------------------------------------------------------------------

ALTER TABLE messages ADD COLUMN seq        bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE messages ADD COLUMN edited_at  timestamptz;
ALTER TABLE messages ADD COLUMN edit_count integer NOT NULL DEFAULT 0;
ALTER TABLE messages ADD COLUMN thread_id  text REFERENCES threads(id);

CREATE INDEX idx_messages_conversation_seq ON messages (conversation_id, seq);

-- Edit history (append-only metadata trail; content snapshots before each edit)
CREATE TABLE message_edits (
  id          text PRIMARY KEY,
  message_id  text NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  content     text NOT NULL,
  edited_by   text NOT NULL REFERENCES users(id),
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_message_edits_message ON message_edits (message_id, created_at);

ALTER TABLE message_edits ENABLE ROW LEVEL SECURITY;
CREATE POLICY message_edits_owner ON message_edits
  USING (EXISTS (
    SELECT 1 FROM messages m JOIN conversations c ON c.id = m.conversation_id
    WHERE m.id = message_edits.message_id AND c.owner_id = app.uid()
  ));

-- Threads foundation: creator tracking + soft delete
ALTER TABLE threads ADD COLUMN created_by text REFERENCES users(id);
ALTER TABLE threads ADD COLUMN deleted_at timestamptz;

CREATE INDEX idx_threads_parent ON threads (parent_message_id);

-- ---------------------------------------------------------------------------
-- Project activity (audit-style feed, tenant-scoped)
-- ---------------------------------------------------------------------------

CREATE TABLE project_activity (
  id             text PRIMARY KEY,
  project_id     text NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  actor_user_id  text REFERENCES users(id),
  action         text NOT NULL,
  detail         jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_project_activity_project_created ON project_activity (project_id, created_at DESC);

ALTER TABLE project_activity ENABLE ROW LEVEL SECURITY;
CREATE POLICY project_activity_member ON project_activity
  USING (project_id IN (
    SELECT id FROM projects WHERE owner_id = app.uid() OR id IN (
      SELECT project_id FROM project_members WHERE user_id = app.uid()
    )
  ));

-- ---------------------------------------------------------------------------
-- Workspace state / preferences: versioned for conflict detection
-- ---------------------------------------------------------------------------

ALTER TABLE workspace_state ADD COLUMN version bigint NOT NULL DEFAULT 1;
ALTER TABLE user_preferences ADD COLUMN version bigint NOT NULL DEFAULT 1;

CREATE INDEX idx_workspace_state_owner_updated ON workspace_state (owner_id, updated_at DESC);