/**
 * CodeConClave — prefixed, sortable-ish client-safe id generation.
 * Offline/idempotent: ids are client-safe text, never server-generated UUIDs
 * in user-facing tables (per DATABASE CONTRACT).
 */
import { customAlphabet } from 'nanoid';

const alphabet = '0123456789abcdefghijklmnopqrstuvwxyz';
const randomId = customAlphabet(alphabet, 20);

export function newId(prefix: string): string {
  return `${prefix}_${randomId()}`;
}

export const PREFIX = {
  USER: 'usr',
  SESSION: 'ses',
  DEVICE: 'dev',
  TEAM: 'tm',
  PROJECT: 'prj',
  CONVERSATION: 'con',
  MESSAGE: 'msg',
  THREAD: 'thr',
  MEMORY: 'mem',
  DNA: 'dna',
  FILE: 'fil',
  TASK: 'tsk',
  TASK_ATTEMPT: 'atp',
  TASK_STEP: 'stp',
  TOOL_CALL: 'tlc',
  APPROVAL: 'app',
  ARTIFACT: 'art',
  COWORKER_RUN: 'crw',
  HANDOFF: 'hnd',
  TASK_DLQ: 'dlq',
  TASK_DEPENDENCY: 'dep',
  PLAN: 'pln',
  PLAN_ENTRY: 'pne',
  PAYMENT_SESSION: 'pay',
  PAYMENT: 'pmt',
  ENTITLEMENT: 'ent',
  PAYMENT_INTENT: 'pin',
  PAYMENT_EVIDENCE: 'pev',
  PAYMENT_RECONCILIATION: 'prc',
  PAYMENT_DIGEST: 'pdg',
  PLUGIN_CONNECTION: 'plg',
  PLUGIN: 'plg',
  WORKSPACE: 'wsp',
  PREFERENCE: 'pref',
  USAGE_COUNTER: 'usc',
  AUDIT: 'aud',
  EVENT: 'evt',
  OUTBOX: 'out',
  NOTIFICATION: 'ntf',
  EDIT: 'edt',
  JOB: 'job',
  PROJECT_ACTIVITY: 'pact',
  MESSAGE_EDIT: 'medt',
  MENTION: 'mnt',
  USAGE_EVENT: 'use',
  TERMINAL_SESSION: 'tsm',
  TERMINAL_LINE: 'thl',
  REMOTE_SESSION: 'rms',
  STORAGE_META: 'stm',
  AGENT: 'agt',
  AGENT_RUN: 'agn',
  AGENT_DEBATE: 'dbt',
  AGENT_DEBATE_PROPOSAL: 'dbp',
  INSTALLED_AGENT: 'inst',
  AGENT_DECISION: 'dec',
  DECISION_CONFLICT: 'cnf',
  CROSS_PROJECT_PATTERN: 'xpp',
  PREVIEW_SESSION: 'pvw',
  TEAM_INVITATION: 'tiv',
  TEAM_ACTIVITY: 'tact',
  RETURN_TO_WORK: 'rtw',
  IDEA: 'ide',
  IDEA_VOTE: 'ivt',
  IDEA_COMMENT: 'icm',
  BRAINSTORM: 'bsh',
  BRAINSTORM_PARTICIPANT: 'bsp',
  BRAINSTORM_IDEA: 'bsi',
  CLEANUP: 'cln',
  HISTORY_STAR: 'hst',
  DIGEST: 'dig',
  IDEMPOTENCY: 'idk',
  SCHEDULE: 'sch',
  SCHEDULE_RUN: 'scr',
  GOAL: 'gol',
  GOAL_ACTIVITY: 'glac',
  ESCALATION: 'esc',
  AUTOMATION_RULE: 'aut',
  AUTOMATION_RUN: 'arn',
  WORKFLOW_RECIPE: 'wfr',
  WEBHOOK_SECRET: 'whk',
  TASK_CHECKPOINT: 'tcp',
  TASK_BRANCH: 'tbr',
  AUTOPSY: 'aps',
  RECOVERY_HISTORY: 'rch',
  IRREVERSIBLE_ACTION: 'irr',
  PR_SWARM: 'psw',
  REVIEW_FINDING: 'rfd',
  DEP_UPGRADE: 'dug',
  FLAKE_RECORD: 'flk',
  CI_RUN: 'cir',
  PREVIEW_COMMENT: 'pcm',
  PREVIEW_SNAPSHOT: 'psn',
  PROOF_OF_WORK: 'pow',
  PLUGIN_SANDBOX_RUN: 'psb',
  CONTROL_POLICY: 'pol',
  KILL_SWITCH: 'ksw',
  UNDO: 'und',
  SECRET_GUARD_SCAN: 'sgs',
  USAGE_ROLLUP: 'rol',
} as const;